"use client";

// import React, { useContext } from "react";
import { ColorModeContext, ToggleColorMode } from "@/contexts/ThemeContext";
import { CssBaseline, ThemeProvider } from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
// import type { Metadata } from "next";
import { Inconsolata } from "next/font/google";
import React from "react";
import "./globals.css";

const inconsolata = Inconsolata({ subsets: ["latin"], weight: ["400"] });

// const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  const { colorMode, theme } = ToggleColorMode();

  return (
    <html lang="en">
      <body className={inconsolata.className}>
        <ColorModeContext.Provider value={colorMode}>
          <AppRouterCacheProvider>
            <ThemeProvider theme={theme}>
              <CssBaseline />
              {children}
            </ThemeProvider>
          </AppRouterCacheProvider>
        </ColorModeContext.Provider>
      </body>
    </html>
  );
}
